spring.application.name=SpringBoot-mailproj

spring.mail.host=smtp.gmail.com
spring.mail.port=588
spring.mail.username=rangutanmayi2006@gmail.com
spring.mail.password=



spring.mail.properties.mail.smtp.auto=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=8082
